# Generated by Django 2.2.3 on 2019-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190725_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='topping',
            name='allowed',
            field=models.ManyToManyField(null=True, related_name='toppings', to='orders.Item'),
        ),
    ]
