# Generated by Django 2.2.3 on 2019-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190725_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Item'),
        ),
    ]
