# Generated by Django 2.2.3 on 2019-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190725_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_individual',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
    ]
