# Generated by Django 2.2.3 on 2019-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_status_friendly_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='selected_toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='orders.Topping'),
        ),
    ]
