# Generated by Django 2.2.3 on 2019-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='orders.Topping'),
        ),
    ]
