# Generated by Django 2.2.3 on 2019-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20190729_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_on_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
