# Generated by Django 2.2.3 on 2019-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Order'),
        ),
    ]
