# Generated by Django 2.2.3 on 2019-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Item'),
        ),
    ]
