# Generated by Django 2.2.3 on 2019-07-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190725_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='allowed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
    ]
