# Generated by Django 2.2.3 on 2019-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_topping_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'allowed': True}, related_name='items', to='orders.Topping'),
        ),
        migrations.RemoveField(
            model_name='topping',
            name='allowed',
        ),
        migrations.AddField(
            model_name='topping',
            name='allowed',
            field=models.ManyToManyField(null=True, to='orders.Item'),
        ),
    ]
