# Generated by Django 2.2.3 on 2019-07-25 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190725_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='allowed',
            new_name='allowed_on',
        ),
        migrations.AddField(
            model_name='item',
            name='num_toppings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
