# Generated by Django 2.2.3 on 2019-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190725_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_individual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
