# Generated by Django 2.2.3 on 2019-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190726_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='friendly_status',
            field=models.CharField(default='In progress', max_length=32),
            preserve_default=False,
        ),
    ]
