# Generated by Django 2.2.3 on 2019-07-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_category_add_on_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='selected_toppings',
        ),
    ]
